version: '2'
services:
  web:
    build: ./web-server
    command: node /src/dist/src/index.js /config/config.json
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./web-server/vismooc-web-server:/src
      - ./config:/config
    depends_on:
      - db
      - redis
    networks:
      - front-tier
      - back-tier

  data:
    build: ./data-server
    command: python /src/main.py /config/config.json
    volumes:
        - ./data-server/vismooc-data-server:/src
        - ./config:/config
    depends_on:
        - db
    networks:
        - back-tier

  redis:
    image: redis
    networks:
      - back-tier

  db:
    build: ./database
    volumes:
        - ./database/data:/data/db
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
