version: '2'
services:
  recover:
    build: ./recover
    command: mongorestore --host db /data
    volumes:
      - ./database/data_backup:/data
    depends_on:
      - db
    networks:
      - back-tier
  web:
    build: ./web-server
    command: node /src/dist/src/index.js /config/config.json
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./web-server/vismooc-web-server:/src
      - ./config:/config
    depends_on:
      - db
      - redis
  data:
    build: ./data-server
    command: python /src/main.py /config/config.json
    volumes:
        - ./data-server/vismooc-data-server:/src
        - ./config:/config
    depends_on:
        - db
  redis:
    image: redis
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data/db