version: '2'
services:
  web:
    build: ./web-server
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./web-server/dist:/dist
      - ./config:/config
    depends_on:
      - db
      - redis
  data:
    build: ./data-server
    command: python /dist/main.py /config/config.json
    volumes:
        - ./data-server/dist:/dist
        - ./config:/config
    depends_on:
        - db
  redis:
    image: redis
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data