version: '2'
services:
  web:
    build: ./web-server
    command: node ./dist/src/index.js
    ports:
      - "127.0.0.1:9999:9999"

    volumes:
      - ./vismooc-web-server:/src
    depends_on:
      - db
      - redis
    networks:
      - front-tier
      - back-tier

  data:
    extends:
      file: data-server.yaml
      service: data
    links:
        - db
    networks:
        - back-tier
    
  redis:
    image: redis
    networks:
      - back-tier

  db:
    image: mongo
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
