version: '2'
services:
  web:
    build: ./web-server
    image: vismooc-web-server:0.2.0
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./web-server/dist:/dist
      - /dist/node_modules
      - ./config:/config
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  data:
    build: ./data-server
    image: vismooc-data-server:0.13.0
    volumes:
        - ./data-server/dist:/dist
        - /dist/vismooc-test-data
        - ./config:/config
    depends_on:
        - db
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  redis:
    image: redis
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data
