version: '2'
services:
  web:
    build: ./web-server
    image: vismooc-web-server:0.14
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./web-server/dist:/dist
      - /dist/node_modules
      - ./config:/config
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: 1g
        max-file: 10
  data:
    build: ./data-server
    image: vismooc-data-server:0.11
    volumes:
        - ./data-server/dist:/dist
        - ./config:/config
    depends_on:
        - db
    logging:
      driver: json-file
      options:
        max-size: 1g
        max-file: 10
  redis:
    image: redis
    logging:
      driver: json-file
      options:
        max-size: 1g
        max-file: 10
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data
    logging:
      driver: json-file
      options:
        max-size: 1g
        max-file: 10