version: '2'
services:
  web:
    build: .
    command: node ./dist/src/index.js
    ports:
      - "9999:9999"
    volumes:
      - ./vismooc-web-server:/src
    depends_on:
      - db
      - redis
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis
    networks:
      - back-tier

  db:
    image: mongo
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
