export declare function getCoursesById(id: string): Promise<any>;
export declare function getVideosById(id: string): Promise<any>;
export declare function getUsersById(id: string): Promise<any>;
export declare function getVideosByList(videoIds: string[]): Promise<any>;
export declare function getCoursesByList(courseIds: string[]): Promise<any>;
export declare function getCourseIdByVideo(videoId: string): Promise<any>;
export declare function getUsersByList(userIds: string[]): Promise<any>;
export declare function getDenselogsById(videoId: string): Promise<any>;
export declare const getVideoById: Function;
export declare const getCourseById: Function;
export declare const getUserById: Function;
export declare function getCourseStartDate(id: string): Promise<any>;
export declare function getCourseEndDate(id: string): Promise<any>;
